version: "3.4"

services:
  # backend_dev:
  #   build:
  #     context: .
  #     dockerfile: Dev.Dockerfile
  #   restart: always
  #   environment:
  #     TZ: America/Sao_Paulo
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - result-scores

  frontend:
    build:
      context: ./client-app/.
      dockerfile: Dockerfile
    container_name: client-app
    restart: always
    # depends_on:
    #   - backend_dev
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "3333:3000"
    volumes:
      - ./client-app:/app
    networks:
      - result-scores

networks:
  result-scores:
