version: "3.4"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    # restart: always
    environment:
      TZ: America/Sao_Paulo
    command: sleep infinity
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - result-scores

  frontend:
    build:
      context: ./client-app/.
      dockerfile: Dockerfile
    container_name: client-app
    restart: always
    depends_on:
      - backend
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "3333:3000"
    volumes:
      - ./client-app:/app
    networks:
      - result-scores

networks:
  result-scores:
